---

deploy_ioc_use_common: true
deploy_ioc_use_ad_common: false
deploy_ioc_required_module: eurotherm_rtc_43bcabd
deploy_ioc_template_root_path: "{{ deploy_ioc_required_module_path }}"
deploy_ioc_make_autosave_files: true
deploy_ioc_executable: eurotherm_rtc
deploy_ioc_device_specific_env:
  EPICS_DB_INCLUDE_PATH: "$(EUROTHERM_RTC)/db"
