---
deploy_ioc_use_common: true
deploy_ioc_use_ad_common: false
deploy_ioc_required_module: mrftiming_82e4634
deploy_ioc_executable: MRFTiming
deploy_ioc_template_root_path: "{{ deploy_ioc_required_module_path }}"
deploy_ioc_device_specific_env:
  UO_01: "1"
  UO_23: "1"
  UO_01FD: "1"
  UO_23FD: "1"
  TB_01: "1"
  TB_23: "1"
  TB_45: "1"
  TB_67: "1"
  TB_89: "1"
  TB_1011: "1"
  TB_1213: "1"
  TB_1415: "1"
